<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //pen
        DB::table('products')->insert([
            //ballpoints
            ['NameProduct' => 'Uni-Ball One P Limited Edition Amber Color Gel Pen', 'Rating' => 4.5, 'DescriptionProduct' => 'Pulpen gel limited edition dengan warna amber yang elegan dari Uni-Ball, menawarkan pengalaman menulis yang halus dan presisi.', 'SubCategoryProductID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Faber Castell Gel Pen Fast DRY 0.5mm', 'Rating' => 4.7, 'DescriptionProduct' => 'Pulpen gel dari Faber Castell dengan teknologi pengeringan cepat dan ketebalan 0.5mm, sempurna untuk menulis tanpa noda.', 'SubCategoryProductID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Pulpen Gel Motif Fluffy Cartoon Pens Ball Pen Warna Hitam 0.5', 'Rating' => 4.2, 'DescriptionProduct' => 'Pulpen gel dengan motif kartun lucu dan tinta hitam berukuran 0.5mm, cocok untuk menambah keceriaan pada alat tulis Anda.', 'SubCategoryProductID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Pulpen Joyko Gel Cetek Q Gel G P-265', 'Rating' => 4.8, 'DescriptionProduct' => 'Pulpen gel dari Joyko dengan model cetek dan kode G P-265, menawarkan kualitas tinggi dan kenyamanan dalam menulis.', 'SubCategoryProductID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Typo - Gel Pens 7Pk - Pastel', 'Rating' => 4.9, 'DescriptionProduct' => 'Set pulpen gel dari Typo yang terdiri dari 7 warna pastel, ideal untuk membuat catatan yang penuh warna dan kreatif.', 'SubCategoryProductID' => 1, 'created_at' => now(), 'updated_at' => now()],
            //fountain
            ['NameProduct' => 'MONTEVERDE Ritma Fountain Pen', 'Rating' => 3.9, 'DescriptionProduct' => 'MONTEVERDE Ritma Fountain Pen adalah pulpen mewah dengan desain minimalis dan modern yang terinspirasi dari bentuk geometris. Pulpen ini menawarkan keseimbangan sempurna dan kenyamanan menulis yang luar biasa. Dilengkapi dengan nib berkualitas tinggi, pulpen ini cocok untuk kolektor maupun profesional.', 'SubCategoryProductID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Parker 15 Energy Blue', 'Rating' => 4.2, 'DescriptionProduct' => 'Parker 15 Energy Blue adalah pulpen yang memadukan keanggunan dengan kinerja. Dengan desain yang ramping dan warna biru yang mencolok, pulpen ini memberikan pengalaman menulis yang halus dan konsisten. Ideal untuk penggunaan sehari-hari maupun sebagai hadiah eksklusif.', 'SubCategoryProductID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Diamine 30ml Fountain Pen Ink', 'Rating' => 3.5, 'DescriptionProduct' => 'Diamine 30ml Fountain Pen Ink adalah tinta berkualitas tinggi yang cocok untuk berbagai jenis pulpen fountain. Dengan konsistensi yang sempurna dan pilihan warna yang beragam, tinta ini memastikan tulisan yang jelas dan bebas dari noda. Tinta ini juga ramah lingkungan dan tidak mudah kering.', 'SubCategoryProductID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Pulpen Pilot Fountain Pen Birdie S70SS Medium Original Jepang', 'Rating' => 4.5, 'DescriptionProduct' => 'Pulpen Pilot Fountain Pen Birdie S70SS Medium Original Jepang adalah pilihan terbaik bagi pecinta alat tulis Jepang. Dikenal dengan kualitasnya yang superior, pulpen ini menawarkan tulisan yang halus dan tahan lama. Desainnya yang elegan dan ringan membuatnya nyaman digunakan sepanjang hari.', 'SubCategoryProductID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Kaweco Perkeo Fountain Pen', 'Rating' => 4.1, 'DescriptionProduct' => 'Kaweco Perkeo Fountain Pen adalah pulpen dengan desain klasik dan ergonomis. Terbuat dari bahan berkualitas tinggi, pulpen ini menawarkan pengalaman menulis yang nyaman dan stabil. Tersedia dalam berbagai warna, pulpen ini cocok untuk pelajar, profesional, dan kolektor.', 'SubCategoryProductID' => 2, 'created_at' => now(), 'updated_at' => now()],
            //marker
            ['NameProduct' => 'Joyko Marker Penanda Spidol', 'Rating' => 2.9, 'DescriptionProduct' => 'Joyko Marker Penanda Spidol adalah spidol serbaguna yang ideal untuk berbagai kebutuhan penandaan. Dengan tinta yang cepat kering dan tahan lama, spidol ini sangat cocok untuk digunakan di berbagai permukaan seperti kertas, karton, dan plastik. Desainnya yang ergonomis memastikan kenyamanan dalam penggunaan jangka panjang.', 'SubCategoryProductID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Outline Markers Double line Outline Pen Drawing Marker Pen', 'Rating' => 2.8, 'DescriptionProduct' => 'Outline Markers Double line Outline Pen Drawing Marker Pen adalah alat yang sempurna untuk menambahkan sentuhan kreatif pada proyek seni Anda. Spidol ini memiliki dua garis tinta yang memberikan efek outline otomatis, membuat gambar dan tulisan Anda terlihat lebih menarik dan unik.', 'SubCategoryProductID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Spidol Permanent SNOWMAN', 'Rating' => 4.9, 'DescriptionProduct' => 'Spidol Permanent SNOWMAN adalah pilihan terbaik untuk kebutuhan penandaan permanen. Dengan tinta yang tahan air dan cepat kering, spidol ini dapat digunakan di berbagai permukaan seperti plastik, logam, dan kaca. Kualitas tinggi dari tinta memastikan hasil yang tajam dan jelas.', 'SubCategoryProductID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Spidol Penanda Kain / Water Erasable Pen / Fabric Marker', 'Rating' => 4.5, 'DescriptionProduct' => 'Spidol Penanda Kain / Water Erasable Pen / Fabric Marker adalah alat yang sempurna untuk proyek menjahit dan kerajinan tangan. Tinta yang dapat dihapus dengan air memudahkan Anda dalam membuat tanda sementara pada kain tanpa meninggalkan noda permanen. Ideal untuk penjahit dan pengrajin.', 'SubCategoryProductID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'ZEBRA MILDLINER BRUSH PEN & MARKER DOUBLE ENDED HIGHLIGHT', 'Rating' => 4.9, 'DescriptionProduct' => 'ZEBRA MILDLINER BRUSH PEN & MARKER DOUBLE ENDED HIGHLIGHT adalah alat tulis yang menawarkan dua fungsi dalam satu produk. Satu ujung berupa brush pen yang fleksibel untuk membuat garis tebal dan tipis, sementara ujung lainnya berupa highlighter untuk penandaan. Tersedia dalam berbagai warna pastel yang lembut, spidol ini sempurna untuk perencanaan kreatif dan jurnal.', 'SubCategoryProductID' => 3, 'created_at' => now(), 'updated_at' => now()],
            //specialty 
            ['NameProduct' => 'Zebra Prestige Fineliner', 'Rating' => 3.9, 'DescriptionProduct' => 'Zebra Prestige Fineliner adalah pulpen fineliner berkualitas tinggi yang ideal untuk menulis, menggambar, dan sketsa. Dengan ujung yang halus dan tinta yang tahan lama, fineliner ini menawarkan garis yang konsisten dan tajam setiap kali digunakan. Desainnya yang elegan dan ergonomis membuatnya nyaman untuk digunakan dalam jangka waktu lama.', 'SubCategoryProductID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Haile 4Size STA Waterproof Calligraphy Pen', 'Rating' => 3.4, 'DescriptionProduct' => 'Haile 4Size STA Waterproof Calligraphy Pen adalah set pena kaligrafi dengan empat ukuran berbeda, dirancang untuk memenuhi kebutuhan seni tulis tangan dan kaligrafi Anda. Tinta tahan air memastikan hasil tulisan yang tahan lama dan tidak luntur. Pena ini sempurna untuk menciptakan karya kaligrafi yang indah dan detail.', 'SubCategoryProductID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'Baru Calligraphy Pens - 4 Sizes Calligraphy', 'Rating' => 4.7, 'DescriptionProduct' => 'Baru Calligraphy Pens - 4 Sizes Calligraphy adalah set pena kaligrafi yang terdiri dari empat ukuran berbeda untuk berbagai gaya tulisan. Set ini ideal untuk pemula maupun profesional yang ingin menghasilkan karya kaligrafi yang menakjubkan. Tinta berkualitas tinggi memastikan setiap goresan terlihat jelas dan tajam.', 'SubCategoryProductID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'KENKO - Pulpen Gel Bisa Dihapus T-Gel Erasable KE-303ER', 'Rating' => 4.3, 'DescriptionProduct' => 'KENKO - Pulpen Gel Bisa Dihapus T-Gel Erasable KE-303ER adalah pulpen gel inovatif yang memungkinkan Anda menghapus tinta dengan mudah tanpa meninggalkan bekas. Ideal untuk menulis catatan dan dokumen yang memerlukan koreksi. Desain ergonomis dan tinta yang halus membuat pengalaman menulis menjadi lebih menyenangkan.', 'SubCategoryProductID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['NameProduct' => 'PILOT FRIXION CLICKER 3 IN 1 ERASABLE PEN', 'Rating' => 3.6, 'DescriptionProduct' => 'PILOT FRIXION CLICKER 3 IN 1 ERASABLE PEN adalah pulpen multifungsi dengan tiga warna tinta yang dapat dihapus. Ideal untuk membuat catatan berwarna, mengorganisir dokumen, dan menandai kalender. Teknologi penghapusan unik memungkinkan Anda mengoreksi kesalahan dengan mudah, menjadikannya alat yang sangat berguna untuk pelajar dan profesional.', 'SubCategoryProductID' => 4, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
